trigger:
  batch: true
  branches:
    include:
      - azureIntegration

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Maven_Stage
    displayName: Install JDK21 with Maven Install
    jobs:
      - job: Maven_Stage
        displayName: Maven Stage
        pool:
          name: Default
        steps:
          - script: |
              sudo apt-get update
              sudo apt-get install -y openjdk-21-jdk
            displayName: 'Install OpenJDK 21'
          - task: Maven@3
            inputs:
              mavenPomFile: '$(Build.SourcesDirectory)/library-database-books-example/pom.xml'
              mavenOptions: '-Xmx3072m'
              mavenAuthenticateFeed: false
              goals: 'clean install'
              options: '-B'
            displayName: 'Maven clean install'
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'BuildDatabase JAR'
              itemPattern: '$(System.ArtifactsDirectory)/library-database-books-example/target/librarydatabase.jar'
              targetPath: '$(Pipeline.Workspace)'
  - stage: Build_and_Push_Stage
    displayName: Build_and_Push_Stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: Default
        steps:
          - task: DownloadBuildArtifacts@1
            displayName: Download JAR File LibraryDatabase
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'BuildDatabase JAR'
              downloadPath: '$(System.ArtifactsDirectory)/library-database-books-example/target'
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/library-database-books-example/Dockerfile'
              tags: |
                $(tag)
