trigger:
  - azureIntegration

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Maven Stage
    displayName: Install JDK21 with Maven Install
    jobs:
      - job: Maven Stage
        displayName: Maven Stage
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              sudo apt-get update
              sudo apt-get install -y openjdk-21-jdk
            displayName: 'Install OpenJDK 21'
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.21'
              mavenOptions: '-Xmx3072m'
              mavenAuthenticateFeed: false
              goals: 'clean install'
              workingDirectory: '$(Build.SourcesDirectory)/library-database-books-example/library-database-books-example'
            displayName: 'Maven clean install'
  - stage: Build and Push Stage
    displayName: Build and Push Stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/library-database-books-example/library-database-books-example/Dockerfile'
              tags: |
                $(tag)
