trigger:
  batch: true
  branches:
    include:
      - azureIntegration

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Maven_Stage
    displayName: Maven Stage
    jobs:
      - job: Maven_Stage
        displayName: JDK21 Install and Maven Build
        pool:
          name: Default
        steps:
          - script: |
              sudo apt-get update
              sudo apt-get install -y openjdk-21-jdk
            displayName: 'Install OpenJDK 21'
          - task: Maven@3
            inputs:
              mavenPomFile: '$(Build.SourcesDirectory)/library-database-books-example/pom.xml'
              mavenOptions: '-Xmx3072m'
              mavenAuthenticateFeed: false
              goals: 'clean install'
              options: '-B'
            displayName: 'Mvn Install LibraryDatabase'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)/library-database-books-example/target/librarydatabase.jar'
              artifact: 'librarydatabase.jar'
            displayName: 'Publish Artifact LibraryDatabase'
          - task: Maven@3
            inputs:
              mavenPomFile: '$(Build.SourcesDirectory)/library-loan-notloan-example/pom.xml'
              mavenOptions: '-Xmx3072m'
              mavenAuthenticateFeed: false
              goals: 'clean install'
              options: '-B'
            displayName: 'Mvn Install LibraryLoan'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)/library-loan-notloan-example/target/libraryloan.jar'
              artifact: 'libraryloan.jar'
            displayName: 'Publish Artifact LibraryLoan'
  - stage: Build_and_Push_Stage
    displayName: Build and Push Stage
    jobs:
      - job: Build
        displayName: Build and Push on Gitlab
        pool:
          name: Default
        steps:
          - task: DownloadBuildArtifacts@1
            displayName: Download Artifact LibraryDatabase
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'librarydatabase.jar'
              downloadPath: '$(Build.SourcesDirectory)/library-database-books-example/target/'
          - task: DownloadBuildArtifacts@1
            displayName: Download Artifact LibraryLoan
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'libraryloan.jar'
              downloadPath: '$(Build.SourcesDirectory)/library-loan-notloan-example/target/'
          - task: Docker@2
            displayName: Build an image
            inputs:
              containerRegistry: 'Gitlab'
              command: buildAndPush
              repository: 'infrastructure4143511/library-operation-loan-example'
              dockerfile: '$(Build.SourcesDirectory)/library-database-books-example/Dockerfile'
              tags: 'library-database-azurerelease'
          - task: Docker@2
            displayName: Build an image
            inputs:
              containerRegistry: 'Gitlab'
              command: buildAndPush
              repository: 'infrastructure4143511/library-operation-loan-example'
              dockerfile: '$(Build.SourcesDirectory)/library-loan-notloan-example/Dockerfile'
              tags: 'library-loan-azurerelease'
          
